---
project: ZTP
credentials:
  provision:
    username: provision
    password: provision
swversions:
  "9300":
    version: "16.12.04"
    image: cat9k_iosxe.16.12.04.SPA.bin
  "3650":
    version: "16.09.06"
    image: cat3k_caa-universalk9.16.09.06.SPA.bin
  c3750:
    version: "12.2(55)SE8"
    image: c3750-ipbasek9-tar.122-55.SE8.tar
    size: 15923200