version: '3.8'

services:
  dhcp:
    container_name: dhcp
    image: kosdk/dhcpd
    network_mode: host
    volumes:
      - ./dhcp:/data
  tftp:
    container_name: tftp
    build: ./provisioning
    ports:
      - "69:69/udp"
    networks:
      - backend
    volumes:
      - ./files:/usr/src/tftproot
  # ftp:
  #   container_name: ftp
  #   image: instantlinux/vsftpd
  #   ports:
  #     - "20-21:20-21"
  #     - "30091-30100:30091-30100"
  #   environment: 
  #     - ANONYMOUS_ENABLE=YES
  #     - PASV_ADDRESS=10.0.0.1
  #   volumes:
  #     - ./files:/var/lib/ftp
  http:
    container_name: http
    image: nginx:alpine
    volumes:
      - ./files:/files
      - ./http/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - backend

networks:
  backend: