version: '3.8'

services:
  # traefik:
  #   container_name: traefik
  #   image: traefik
  #   networks:
  #     - proxy
  #     - webservices
  #   command:
  #     - --log.level=INFO
  #     - --providers.docker=true
  #     - --providers.docker.exposedbydefault=false
  #     - --entrypoints.web.address=:80
  #     - --api.insecure=true
  #     - --api
  #   ports:
  #     - 80:80
  #     - 8080:8080
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  # api:
  #   container_name: api
  #   build: ./backend
  #   command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
  #   expose:
  #     - 80
  #   networks:
  #     - webservices
  #     - backend
  #   volumes:
  #     - ./backend:/usr/src/app
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/docs`)
  #     - traefik.http.routers.api.entrypoints=web
  #     - traefik.port=80
  files:
    container_name: files
    image: nginx:alpine
    # networks:
    #   - webservices
    ports:
      - 80:80
    volumes:
      - ./files:/files
      - ./http/default.conf:/etc/nginx/conf.d/default.conf
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.files.rule=PathPrefix(`/files`)
  #     - traefik.http.routers.files.entrypoints=web
  #     - traefik.port=80
  dhcp:
    container_name: dhcp
    image: kosdk/dhcpd
    network_mode: host
    volumes:
      - ./dhcp:/data
  tftp:
    container_name: tftp
    build: 
      context: ./provisioning
      dockerfile: Dockerfile.tftp
    ports:
      - 69:69/udp
    networks:
      - tftp
      - backend
    volumes:
      - ./files:/usr/src/tftproot
      - ./config.yaml:/usr/src/app/config.yaml
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    networks:
      - backend
  # flower:
  #   container_name: flower
  #   build: ./flower
  #   ports:
  #     - 49555:5555
  #   networks:
  #     - proxy
  #     - backend
  #   command:
  #     - "--broker=amqp://guest@rabbitmq:5672/"
  clearly-server:
    image: rsalmei/clearly
    container_name: clearly-server
    ports:
      - 12223:12223
    networks:
      - proxy
      - backend
    command: server amqp://guest@rabbitmq:5672/ --backend redis://redis/0
    depends_on: 
      - rabbitmq
    restart: on-failure
  worker:
    build:
      context: ./provisioning
      dockerfile: Dockerfile.worker
    networks:
      - backend
    entrypoint: celery -A celery_app.tasks worker -E -c 4 -l DEBUG -Q provision -n provision

networks:
  proxy:
    external: true
  tftp:
    external: true
#   webservices:
#     external: false
  backend:
    external: false