version: '3.7'

services:
  dhcp:
    container_name: dhcp
    image: kosdk/dhcpd
    network_mode: host
    volumes:
      - ./dhcp:/data
  tftp:
    container_name: tftp
    build: ./provisioning
    network_mode: host
    volumes:
      - ./provisioning/tftproot:/tftproot
