version: '3.8'

services:
  dhcp:
    container_name: dhcp
    image: kosdk/dhcpd
    network_mode: host
    volumes:
      - ./dhcp:/data
  tftp:
    container_name: tftp
    build: ./provisioning
    ports:
      - "69:69/udp"
    networks:
      - backend
    volumes:
      - ./provisioning/tftproot:/usr/src/tftproot
  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - backend

networks:
  backend: