FROM python:3.8-slim-buster

RUN apt-get update && apt-get install -y iputils-ping && pip install --upgrade pip

WORKDIR /usr/src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements-celery.txt .
RUN pip install -r requirements-celery.txt

COPY ./tftp ./app

WORKDIR /usr/src/app