FROM python:3.8-slim-buster
RUN apt-get update && apt-get install -y gcc python3-dev iputils-ping curl && pip install --upgrade pip

WORKDIR /usr/src

COPY requirements-tftp.txt .
RUN pip install -r requirements-tftp.txt

COPY ./tftp ./app

WORKDIR /usr/src/app

ENTRYPOINT ["python", "tftp_server.py"]